export const LOGOUT = "LOGOUT";
export const GET_PROFILE_INFO = "GET_PROFILE_INFO";
export const EDIT_PROFILE_INFO = "EDIT_PROFILE_INFO";
export const CHANGE_PROFILE_PHOTO = "CHANGE_PROFILE_PHOTO";

export const SELECT__UPLOAD__PHOTO = "SELECT__UPLOAD__PHOTO";
export const CLEAR__SELECT__UPLOAD__PHOTO = "CLEAR__SELECT__UPLOAD__PHOTO";