export const LOGOUT = "LOGOUT";
export const GET_PROFILE_INFO = "GET_PROFILE_INFO";
export const EDIT_PROFILE_INFO = "EDIT_PROFILE_INFO";
export const CHANGE_PROFILE_PHOTO = "CHANGE_PROFILE_PHOTO";

export const SELECT__UPLOAD__PHOTO = "SELECT__UPLOAD__PHOTO";
export const CLEAR__SELECT__UPLOAD__PHOTO = "CLEAR__SELECT__UPLOAD__PHOTO";

export const SET_EDITED_PHOTO = "SET_EDITED_PHOTO";
export const CLEAR_SET_EDITED_PHOTO = "CLEAR_SET_EDITED_PHOTO";
export const TOGGOLE_DONE_PHOTO_EDITING = "TOGGOLE_DONE_PHOTO_EDITING";
export const PHOTO_CAPTION = "PHOTO_CAPTION";
export const GET_ALL_PHOTOS = "GET_ALL_PHOTOS";
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const SET_FILTER = "SET_FILTER";